### ISSUE TITLE
MPI_comm problem

### ISSUE THREAD

**Issue by cnegre** [qmmd/bml#21]
I get this error when compiling the last commit in the develop branch:

In file included from /home/christian/bml/src/C-interface/ellpack/bml_parallel_ellpack_typed.c:3:0:
/home/christian/bml/src/C-interface/./bml_parallel.h:20:1: error: unknown type name ‘MPI_Comm’
 extern MPI_Comm ccomm;
 ^
make[2]: **\* [src/C-interface/ellpack/CMakeFiles/bml-ellpack-double_complex.dir/bml_parallel_ellpack_typed.c.o] Error 1
make[1]: **\* [src/C-interface/ellpack/CMakeFiles/bml-ellpack-double_complex.dir/all] Error 2
make: **\* [all] Error 2
christian@christian-Latitude-E6540:~/bml/build$

**Comment by nicolasbock** [comment]
This problem is fixed with Sue's latest commit.
