### ISSUE TITLE
realloc_lhs flag for ifort compiler missing

### ISSUE THREAD

**Issue by aradi** [qmmd/bml#9]
When compiling with the ifort compiler (ifort 15), the automatic reallocation of allocatables on the LHS (which is a standard Fortran 2003 feature) is not turned on (ifort would explicitly need the '-assume realloc_lhs' flag to enable it). Without this flag, the valid F2003 assignment `a_dense = a_dense_ptr` in bml_convert_m.F90 is ill defined and makes several tests to fail.

**Comment by nicolasbock** [comment]
I was afraid of that, but hadn't had time yet to look into it. Do you know whether ifort defines a macro to test whether it is re-allocating the LHS or not?

**Comment by nicolasbock** [comment]
Well, It's probably easiest to throw the appropriate flag into ifort's defaults.

**Comment by aradi** [comment]
I think it is a good idea to add it as a default flag. I've never understood, why you need an extra flag to enforce standard compliance...

**Comment by nicolasbock** [comment]
Me neither :)
